#!/usr/bin/env python3
"""Convert the supplied Rock-Ola Nibbler ROM set into Galagino Plus headers."""
from pathlib import Path
import sys
import zipfile
import zlib

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
ARCHIVE = ROOT / "romszip" / "nibbler.zip"
OUT_DIR = ROOT / "source" / "src" / "machines" / "nibbler"

MANIFEST = {
    "g960-52.12": (0x1000, 0xAC6A802B),
    "g960-48.07": (0x1000, 0x35971364),
    "g960-49.08": (0x1000, 0x6B33B806),
    "g960-50.09": (0x1000, 0x91A4F98D),
    "g960-51.10": (0x1000, 0xA151D934),
    "g960-53.14": (0x1000, 0x063F05CC),
    "g960-54.15": (0x1000, 0x7205FB8D),
    "g960-55.16": (0x1000, 0x4BB39815),
    "g960-56.17": (0x1000, 0xED680F19),
    "g960-57.50": (0x1000, 0x01D4D0C2),
    "g960-58.51": (0x1000, 0xFEFF7FAF),
    "g70805.ic7": (0x0020, 0xA5709FF3),
    "g70804.ic6": (0x0020, 0xDACD592D),
    "g959-43.51": (0x0800, 0x0345F8B7),
    "g959-44.52": (0x0800, 0x87D67DEE),
    "g959-45.53": (0x0800, 0x33189917),
}

def load(archive: zipfile.ZipFile, name: str) -> bytes:
    try:
        data = archive.read(name)
    except KeyError:
        sys.exit(f"ERROR: missing {name} in {ARCHIVE}")
    size, expected_crc = MANIFEST[name]
    crc = zlib.crc32(data) & 0xffffffff
    if len(data) != size:
        sys.exit(f"ERROR: {name}: expected {size:#x} bytes, got {len(data):#x}")
    if crc != expected_crc:
        sys.exit(f"ERROR: {name}: CRC32 {crc:08X}, expected {expected_crc:08X}")
    return data

def write_header(filename: str, symbol: str, data: bytes, description: str) -> None:
    path = OUT_DIR / filename
    with path.open("w", newline="\n") as out:
        out.write("// Generated by romconv/nibbler/nibbler_rom_convert.py; do not edit.\n")
        out.write(f"// {description}\n")
        out.write(f"const unsigned char {symbol}[] = {{\n")
        for offset in range(0, len(data), 16):
            out.write("  " + ",".join(f"0x{x:02x}" for x in data[offset:offset+16]) + ",\n")
        out.write("};\n")
    print(f"  wrote {path.name}: {len(data):#x} bytes")

def main() -> None:
    if not ARCHIVE.exists():
        sys.exit(f"ERROR: missing ROM archive: {ARCHIVE}")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(ARCHIVE) as archive:
        program = b"".join(load(archive, name) for name in (
            "g960-52.12", "g960-48.07", "g960-49.08", "g960-50.09", "g960-51.10",
            "g960-53.14", "g960-54.15", "g960-55.16", "g960-56.17"))
        gfx = load(archive, "g960-57.50") + load(archive, "g960-58.51")
        proms = load(archive, "g70805.ic7") + load(archive, "g70804.ic6")
        sound = load(archive, "g959-43.51") + load(archive, "g959-44.52") + load(archive, "g959-45.53")
    write_header("nibbler_rom.h", "nibbler_rom", program,
                 "Revision 6 main M6502 ROMs at 0x3000-0xbfff; IC14 is mirrored at 0xf000.")
    write_header("nibbler_gfx.h", "nibbler_gfx", gfx,
                 "Fixed graphics: 512 characters, 8x8, 2 bpp, separated bitplanes.")
    write_header("nibbler_proms.h", "nibbler_proms", proms,
                 "64-byte foreground/background palette PROMs.")
    write_header("nibbler_sound_rom.h", "nibbler_sound_rom", sound,
                 "Three 2 KiB music ROMs used by the SNK 6502 sound sequencer.")
    print("Nibbler conversion complete.")

if __name__ == "__main__":
    main()
